# -------------------------------
# Configuration Netlify pour Flutter Web + Supabase
# -------------------------------

[build]
  # Commande corrigée (plus de --no-wasm)
  command = """
    export PATH="$PATH:$(pwd)/flutter/bin" &&
    flutter config --enable-web &&
    flutter pub get &&
    flutter build web --release
  """
  
  publish = "build/web"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "AIza"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200